### ISSUE TITLE
Issue running project on Xcode 9.1

### ISSUE THREAD

**Issue by BilalReffas** [BenchR267/ParserCombinator#21]
After cloning the project I'm running in some issues using the latest Xcode (9.1).

```
Playground execution failed:

error: Parsel.playground:10:20: error: use of undeclared type 'ParseError'
enum ParsingError: ParseError {
                   ^~~~~~~~~~

error: Parsel.playground:10:6: error: type 'ParsingError' does not conform to protocol 'RawRepresentable'
enum ParsingError: ParseError {
     ^

error: Parsel.playground:15:17: error: use of unresolved identifier 'Parser'
let character = Parser<String, Character> { input in
```

It seems like Xcode have some issues to find `ParseError` and `Parser` etc.

**Comment by BenchR267** [comment]
Thanks for the issue, this is intended. The playground contains all source files the project contains. But to don't have them doubled in the repository, the playground is generated. To make the project working, you need to run `make initial` first, that generates all necessary files (+ copies the ones needed for the playground into the correct folder).
The playground is meant to be downloaded from the [release page](https://github.com/BenchR267/Parsel/releases/latest). To play around with the project, please use the attached playground there.

But thanks for the hint! I added the explanation to the README file in 8a5c6b11.

**Comment by BilalReffas** [comment]
Awesome it works now 👍
