### ISSUE TITLE
ignoring whitespace

### ISSUE THREAD

**Issue by wildthink** [BenchR267/ParserCombinator#23]
What is the canonical way to ignore whitespace say to that "3 + 4" and "3+4" will parse to the same structure?
Thanks.

**Comment by BenchR267** [comment]
Hey @wildthink, thanks for reaching out!
I think, that depends on your grammer. You could define number to have an optional and variable number of spaces trailing them likes this:

```Swift
let number = L.decimalNumber <~ L.space.rep
let addition = number <~ L.plus ~ number ^^ (+)

dump(addition.parse("3+ 5"))
```

Or, if you would like to only allow one or no space:
```Swift
let number = L.decimalNumber <~ L.space.optional
```

You could also define the operator to have one optional space around them like this:

```Swift
func op(_ o: Parser<String, Character>) -> Parser<String, Character> {
    return L.space.optional ~> o <~ L.space.optional
}

let addition = L.decimalNumber <~ op(L.plus) ~ L.decimalNumber ^^ (+)

dump(addition.parse("3 +5"))
```

Here you can as well use `rep` instead of `optional` if you would like to allow multiple spaces as well.

I would prefer the last one, but it depends on you :)

**Comment by wildthink** [comment]
Ah. Thanks. As a general rule do you think its better to eat all the ending whitespace of a token as opposed to the optional surrounding space func above?

If I want to create an AST would I define a Parser <String, ASTNode> or such? Or is something like it a byproduct of the standard parse?

thx

**Comment by BenchR267** [comment]
I think it's hard to answer that in general speaking. I personally think that surrounding spaces around operators often improve readability a lot but on the other hand it might not be a good idea to force that by the compiler but by code styles.

If you would like to create an AST I would suggest to not go straight from String to ASTNode but to consume the input in two steps: first by lexing it with a Parser of type `Parser<String, Token>` where `Token` is an enum with similiar structure to [this](https://github.com/BenchR267/SwiftTranspiler/blob/master/Sources/Core/Token.swift). Then, in second step, you would define the parser itself which consumes a sequence of `Token`s and produces the AST. The type would be `Parser<[Token], ASTNode>` or _(depending on your AST implementation)_ `Parser<[Token], ASTProgram>` where `ASTProgram` would be a wrapper for a list of `ASTStatement` for example.

I'm currently in the process of rewriting my lexer and parser for 'Get Schwifty' with Parsel, you can also take a look at the source code to get some feeling for it: https://github.com/BenchR267/SwiftTranspiler

**Comment by BenchR267** [comment]
I'll close this as the issue seems to be solved. If you have any further questions, please feel free to open another issue.
